project:
  type: website
  output-dir: _site

website:
  title: "The ABC of AKM"
  repo-url: https://github.com/tlamadon/abc-of-akm
  repo-actions: [source, issue]
  navbar:
    left:
      - href: jep.ipynb
        text: Notebook
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/tlamadon/abc-of-akm

execute:
  enabled: true

format:
  html:
    theme: zephyr
    toc: true
    toc-depth: 3
    code-fold: true
